import { Content } from '../types';

export const CONTENT_ES: Content = {
  metadata: {
    title: 'Portafolio Profesional - Desarrollador Full Stack',
    description: 'Portafolio profesional de desarrollador con estética hacker',
  },
  nav: {
    about: 'Acerca de',
    techSkills: 'Habilidades Técnicas',
    softSkills: 'Habilidades Blandas',
    certifications: 'Certificaciones',
    projects: 'Proyectos',
    contact: 'Contacto',
  },
  hero: {
    title: 'Desarrollador Full Stack',
    subtitle: 'Construyendo el futuro con código',
    description:
      'Especializado en crear soluciones tecnológicas innovadoras con más de 5 años de experiencia en desarrollo web y móvil.',
    typewriterPhrases: [
      'npm install @confedev/senior-engineer',
      "import { Escalabilidad } from 'felipe-contreras';",
      'console.log("Código, Café, Microservicios");',
      'const [desplegando, setDesplegando] = useState(true);',
      "<ExperienciaNivelSenior sectores={['Retail', 'Banca']} />",
      'await felipe.optimizar(codigoLegado);',
      'npx crear-app-con-impacto --felipe-contreras',
      "estandarizacion.aplicar({ herramientas: ['Nx', 'IA'] });",
      "{{ 'Felipe' | translate: 'Experto Fullstack' }}",
      'System.out.println("Arquitectura para Escalar");',
      'SpringApplication.run(FelipeContreras.class);',
      '@Autowired private Innovacion innovacion;',
      'public class Solucion implements EscalableEnNube {}',
      'mvn clean install felipe-contreras',
      'while(problema.existe()) { felipe.resolver(); }',
      'aws lambda invoke --function resolverProblemas',
      'git commit -m "feat: el futuro del retail"',
      'kubectl get pods -l role=experto',
      'docker run confedev/perfil:latest',
      'terraform apply -target=infraestructura',
      'CI/CD: De Commit a Producción en minutos',
      'ssh felipe@experto-en-nube',
      "SELECT * FROM talento WHERE habilidades = 'Cloud';",
      'pip install soluciones --user felipe',
      'if (usuarioNecesitaEscalabilidad) { usar(felipe); }',
      'history | grep "exito"',
      "process.env.NODE_ENV = 'alto-rendimiento';",
      'modelo.predecir(proximo_gran_proyecto);',
      'nx run-many --target=desplegar',
      '// Menos código, más soluciones.',
      "estandarizacion.aplicar({ herramientas: ['IA'] });",
      'gen_ai.generar(soluciones_innovadoras);',
      'agente_ia.optimizar(flujo_trabajo);',
      'red_neuronal.entrenar(arquitectura_escalable);',
    ],
  },
  about: {
    title: 'Acerca de Mí',
    content:
      'Soy un desarrollador apasionado por la tecnología y la innovación. Me especializo en crear aplicaciones web y móviles robustas y escalables. Mi enfoque está en escribir código limpio, mantenible y eficiente.',
  },
  techSkills: {
    title: 'Habilidades Técnicas',
    all: 'Todas',
  },
  softSkills: {
    title: 'Habilidades Blandas',
    all: 'Todas',
  },
  certifications: {
    title: 'Certificaciones',
    all: 'Todas',
  },
  projects: {
    title: 'Proyectos',
  },
  contact: {
    title: 'Contacto',
    email: 'email@ejemplo.com',
    phone: '+1 234 567 890',
    phoneLabel: 'Teléfono',
    location: 'Ciudad, País',
    locationLabel: 'Ubicación',
  },
  filters: {
    all: 'Todas',
  },
  footer: {
    description: 'Hecho con ❤️ y mucho ☕ (+ una pizca de 🤖)',
  },
  contactModal: {
    title: 'Enviar Mensaje',
    description:
      'Completa el formulario y me pondré en contacto contigo pronto.',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo Electrónico',
    company: 'Empresa',
    phone: 'Teléfono',
    optional: '(opcional)',
    send: 'Enviar Mensaje',
    cancel: 'Cancelar',
    sending: 'Enviando...',
    success: '¡Mensaje Enviado!',
    successMessage:
      'Tu mensaje ha sido enviado correctamente. Te responderé pronto.',
    error: 'Error al Enviar',
    errorMessage: 'Hubo un problema al enviar tu mensaje. Inténtalo de nuevo.',
    required: 'Este campo es obligatorio',
    invalidEmail: 'Ingresa un correo electrónico válido',
    tryAgain: 'Intentar de nuevo',
    autoCloseMessage: 'Este modal se cerrará automáticamente...',
  },
};
